options {
    listen-on port 53 { any; };
    listen-on-v6 port 53 { any; };
    directory       "/var/named";
    dump-file       "/var/named/data/cache_dump.db";
    statistics-file "/var/named/data/named_stats.txt";
    memstatistics-file "/var/named/data/named_mem_stats.txt";
    allow-query     { any; };
    recursion no;  # Mejor seguridad para DNS autoritativo

    dnssec-validation yes;
    
    /* Path to ISC DLV key */
    bindkeys-file "/etc/named.root.key";
};

// Zona directa para semita.sv
zone "semita.sv" {
    type master;
    file "/var/named/db.semita.sv";
    allow-update { none; };
};

// Zona inversa para IPv4 172.16.0.0/16
zone "16.172.in-addr.arpa" {
    type master;
    file "/var/named/db.inversav4";
    allow-update { none; };
};

// Zona inversa para IPv6 2001:db7:dea:a::/64
zone "a.0.0.0.a.e.d.0.7.b.d.0.1.0.0.2.ip6.arpa" {
    type master;
    file "/var/named/db.inversav6";
    allow-update { none; };
};

include "/etc/named.rfc1912.zones";
include "/etc/named.root.key";