interface enp0s8
{
    AdvSendAdvert on;
    MinRtrAdvInterval 30;
    MaxRtrAdvInterval 100;

    prefix 2001:db7:dea:a::/64
    {
        AdvOnLink on;
        AdvAutonomous on;   # <-- Habilita SLAAC
    };

    AdvManagedFlag off;      # <-- No obliga a DHCPv6 para la dirección
    AdvOtherConfigFlag on;   # <-- Mantén para entregar DNS, etc.
};
